#!/usr/bin/env bash
# Shares: each seeded share has a corresponding permission on the oCIS drive
# item. User share (view vs edit), group share, link shares (type, passwordless
# present), and expiry. Link passwords are regenerated by oCIS -> assert
# existence/type only, never password equality.

# Resolve the owner's drive id + webdav base + token once (all seeded shares
# are alice's, but this generalizes).
declare -A OWNER_TOKEN OWNER_DRIVE OWNER_WEBDAV
owner_ctx() {
  local owner="$1"
  if [ -z "${OWNER_TOKEN[$owner]:-}" ]; then
    local t; t=$(mint_token "$owner"); OWNER_TOKEN[$owner]="$t"
    OWNER_DRIVE[$owner]="$(user_drive_id "$owner" "$t")"
    OWNER_WEBDAV[$owner]="$(user_drive_webdav "$owner" "$t")"
  fi
}

# item_permissions <owner> <relpath> -> permissions JSON for the drive item.
# The migrated item lives at <webDavUrl>/ownCloud/<relpath>. We resolve its
# item id via the oc:fileid returned by PROPFIND (graph root: path addressing
# is not exposed), then query the permissions endpoint as the owner.
item_permissions() {
  local owner="$1" relpath="$2"
  owner_ctx "$owner"
  local token="${OWNER_TOKEN[$owner]}" drive="${OWNER_DRIVE[$owner]}"
  local wd="${OWNER_WEBDAV[$owner]}" clean="${relpath#/}"
  local fileid
  fileid=$(dav_propfind "$owner" "$token" "$wd/ownCloud/$clean" 0 \
    | grep -o '<oc:fileid>[^<]*</oc:fileid>' | sed 's/<[^>]*>//g' | head -n1)
  [ -n "$fileid" ] || return 1
  ocis_curl "$owner" "$token" "$OCIS_BASE/graph/v1beta1/drives/$drive/items/$fileid/permissions"
}

# FD 3: inner oCIS calls use `docker compose exec` and would eat the CSV stdin.
while IFS=, read -r owner pw path stype recipient perms expire password <&3; do
  case "$owner" in ''|\#*) continue ;; esac

  perm_json=$(item_permissions "$owner" "$path" 2>/dev/null || true)
  label="$owner $path type=$stype recipient=${recipient:-<link>}"

  if [ -z "$perm_json" ]; then
    fail "share present for $label (could not resolve migrated item)"
    continue
  fi

  case "$stype" in
    0) # user share -> a permission granted to the recipient user
       rid=$(ocis_user_id "$recipient")
       DESC="user share to '$recipient' on $path exists"
       grant=$(echo "$perm_json" | jq -c --arg id "$rid" \
         '.value[]? | select(.grantedToV2.user.id==$id)' | head -n1)
       if [ -n "$grant" ]; then pass "$DESC"; else fail "$DESC"; fi
       # Verify the permission mapping: perms 1 = read-only (view), 15 = edit.
       if [ -n "$grant" ]; then
         rn=$(role_name "$(echo "$grant" | jq -r '.roles[0] // empty')")
         case "$perms" in
           1)  DESC="user share on $path is view/read-only (role '$rn')"
               case "$rn" in *view*) pass "$DESC";; *) fail "$DESC";; esac ;;
           15) DESC="user share on $path is editable (role '$rn')"
               case "$rn" in *edit*|*editor*|*write*) pass "$DESC";; *) fail "$DESC";; esac ;;
         esac
       fi
       if [ -n "$expire" ]; then
         DESC="user share on $path has expiration preserved"
         exp=$(echo "$perm_json" | jq -r --arg id "$rid" \
           '.value[]? | select(.grantedToV2.user.id==$id) | .expirationDateTime // empty' | head -n1)
         case "$exp" in "$expire"*) pass "$DESC";; *) fail "$DESC (got '${exp:-none}')";; esac
       fi
       ;;
    1) # group share -> permission granted to the recipient group
       rid=$(ocis_group_id "$recipient")
       DESC="group share to '$recipient' on $path exists"
       found=$(echo "$perm_json" | jq -e --arg id "$rid" \
         '.value[]? | select(.grantedToV2.group.id==$id)' >/dev/null 2>&1 && echo true || echo false)
       assert_true "$found" "$DESC"
       ;;
    3) # public link -> a permission carrying a link object
       DESC="public link on $path exists"
       link=$(echo "$perm_json" | jq -c '.value[]? | select(.link!=null)' | head -n1)
       if [ -n "$link" ]; then pass "$DESC"; else fail "$DESC"; fi
       # Verify the link type: perms 4 = upload-only file-drop -> createOnly,
       # read links -> view. (Link passwords are regenerated by oCIS; not checked.)
       if [ -n "$link" ]; then
         ltype=$(echo "$link" | jq -r '.link.type // empty')
         case "$perms" in
           4) DESC="file-drop link on $path is createOnly (type '$ltype')"
              [ "$ltype" = "createOnly" ] && pass "$DESC" || fail "$DESC" ;;
           *) DESC="read link on $path is view (type '$ltype')"
              [ "$ltype" = "view" ] && pass "$DESC" || fail "$DESC" ;;
         esac
       fi
       ;;
  esac
done 3< fixtures/shares.csv
