<?php
namespace OCA\MigrateToInfiniteScale\Command;

use JsonException;
use OC\Authentication\Token\DefaultTokenProvider;
use OC\Files\Filesystem;
use OC\Files\ObjectStore\ObjectStoreStorage;
use OCA\MigrateToInfiniteScale\Helper\ConflictLogFile;
use OCA\MigrateToInfiniteScale\Helper\OCISClient;
use OCA\MigrateToInfiniteScale\Helper\ProcessOutputLineProcessor;
use OCA\MigrateToInfiniteScale\Helper\UserGroupFinder;
use OCP\IConfig;
use OCP\IURLGenerator;
use OCP\IUser;
use OCP\Share\IManager;
use Ramsey\Uuid\Uuid;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;
use Symfony\Component\Console\Question\ChoiceQuestion;
use Symfony\Component\Process\Process;

class CommandBase extends Command {
	use OutputAware;

	private static string $rclone_bin = __DIR__ . "/../../bin/rclone_linux_amd64";

	protected IConfig $config;
	protected IURLGenerator $generator;
	protected DefaultTokenProvider $tokenProvider;
	protected string $ocis_host;
	protected string $ocis_admin_user;
	protected string $ocis_admin_password;
	protected bool $insecure = false;

	public function preExecute(InputInterface $input): int {
		/*
		if (\OC::$server->getDatabaseConnection()->getDatabasePlatform() instanceof SqlitePlatform) {
			$this->writeln('<error>Sqlite based systems cannot be migrated.</error>');
			return 1;
		}
		*/
		$storage = Filesystem::getStorage('/');
		if ($storage->instanceOfStorage(ObjectStoreStorage::class)) {
			$this->writeln('<error>S3 primary object storage cannot be migrated for the time being.</error>');
			return 1;
		}

		$this->insecure = $input->getOption('insecure');
		# get service id and other configs
		if (!$this->setupDone()) {
			$this->writeln('<error>Please run migrate:to-ocis:init first</error>');
			return 1;
		}

		return 0;
	}

	/**
	 * @throws JsonException
	 */
	protected function getAdminAccessToken(): string {
		# TODO: take care of renewal
		# TODO: no need to get a new token every time
		return $this->actAsUser($this->ocis_admin_user);
	}

	/**
	 * @throws JsonException
	 */
	private function actAsUser(string $user_name): string {
		$client = \OC::$server->getHTTPClientService()->newClient();
		$webdavCS = \OC::$server->getWebDavClientService();
		$client = new OCISClient($client, $webdavCS, $this->ocis_host, $this->insecure);
		return $client->tokenExchange($this->ocis_admin_user, $this->ocis_admin_password, $user_name);
	}

	/**
	 * @throws JsonException
	 */
	private function setupDone(): bool {
		$ocis_host = $this->config->getAppValue('migrate_to_ocis', 'ocis_host', null);
		$this->ocis_host = $ocis_host;

		return true;
	}

	/**
	 * @param InputInterface $input
	 * @param OutputInterface $output
	 * @return void
	 */
	protected function askAdminPassword(InputInterface $input, OutputInterface $output): void {
		/** @var \Symfony\Component\Console\Helper\QuestionHelper $helper */
		$helper = $this->getHelper('question');
		$question = new Question(
			"Password for $this->ocis_admin_user: ",
		);
		$question->setHidden(true);
		$this->ocis_admin_password = $helper->ask($input, $output, $question);
	}

	protected function askForDefaultRole(InputInterface $input, OutputInterface $output, array $apps) {
		/** @var \Symfony\Component\Console\Helper\QuestionHelper $helper */
		$helper = $this->getHelper('question');

		$appsDisplayName = \array_map(function ($app) {
			return $app['displayName'];
		}, $apps);

		$appIndex = 0;
		$chosenApp = $apps[$appIndex];  // it must be at least one app
		if (\count($apps) > 1) {
			$question = new ChoiceQuestion(
				'Choose the app containing the default role',
				// choices can also be PHP objects that implement __toString() method
				$appsDisplayName,
				0
			);
			$appVal = $helper->ask($input, $output, $question);
			$appIndex = \array_search($appVal, $appsDisplayName, true);
			$chosenApp = $apps[$appIndex];
		}

		$rolesDisplayName = \array_map(function ($role) {
			return $role['displayName'];
		}, $chosenApp['appRoles']);

		$roleIndex = 0;
		$chosenRole = $chosenApp['appRoles'][$roleIndex];
		$question = new ChoiceQuestion(
			'Choose the default role',
			// choices can also be PHP objects that implement __toString() method
			$rolesDisplayName,
			0
		);
		$roleVal = $helper->ask($input, $output, $question);
		$roleIndex = \array_search($roleVal, $rolesDisplayName, true);
		$chosenRole = $chosenApp['appRoles'][$roleIndex];

		return [$chosenApp['id'], $chosenRole['id']];
	}

	/**
	 * @param IManager $shareManager
	 * @param IUser $user the OC10 user owning the shares
	 * @param UserGroupFinder $finder to find and cache users and groups
	 * @param array $permissionMap a permission map as generated by SharePermissionMapper->getPermissionMap()
	 * @param OCISClient $ocisClient an oCIS client to perform the needed requests
	 * @param callable $callback a callback to be called after successful share creation.
	 * The method must have the following signature: func(IShare $share, array $jsonResponse)
	 * where the $share is the OC10 share that has been processed and the $jsonReponse is the
	 * oCIS' response to the invite request.
	 */
	protected function createSharesForUser(IManager $shareManager, IUser $user, UserGroupFinder $finder, array $permissionMap, OCISClient $ocisClient, callable $callback) {
		$user_token = $this->ocis_admin_password;
		if ($user->getUID() !== $this->ocis_admin_user) {
			$user_token = $this->actAsUser($user->getUID());
		}

		$personalDrives = $ocisClient->getPersonalDrives($user_token, $user->getUID());
		if (\count($personalDrives) !== 1) {
			// only 1 personal drive is expected, abort otherwise
			return false;
		}

		$shares = \array_merge(
			$shareManager->getSharesBy($user->getUID(), \OCP\Share::SHARE_TYPE_USER, null, true, -1),
			$shareManager->getSharesBy($user->getUID(), \OCP\Share::SHARE_TYPE_GROUP, null, true, -1)
		);
		$webdavClient = $ocisClient->getWebdavClientForDrive($user_token, $user->getUID(), $personalDrives[0]);

		foreach ($shares as $share) {
			$nodePath = $share->getNode()->getPath();
			if (\strpos($nodePath, "/{$user->getUID()}/files/") === 0) {
				$nodePath = \substr($nodePath, \strlen("/{$user->getUID()}/files/"));
			}

			$recipientType = '';
			$recipientId = '';
			if ($share->getShareType() === \OCP\Share::SHARE_TYPE_USER) {
				$recipientType = 'user';
				$recipientId = $finder->getUserById($user_token, $share->getSharedWith());
			} elseif ($share->getShareType() === \OCP\Share::SHARE_TYPE_GROUP) {
				$recipientType = 'group';
				$recipientId = $finder->getGroupById($user_token, $share->getSharedWith());
			}

			// from OC10 neither files or folders can be write-only
			// if they're shared with users or groups
			$nodeType = $share->getNodeType();
			$chosenRole = $permissionMap[$nodeType]['ro'];
			if (
				(($share->getPermissions() & \OCP\Constants::PERMISSION_UPDATE) === \OCP\Constants::PERMISSION_UPDATE) ||
				(($share->getPermissions() & \OCP\Constants::PERMISSION_CREATE) === \OCP\Constants::PERMISSION_CREATE)
			) {
				$chosenRole = $permissionMap[$nodeType]['rw'];
			}

			$ocisFileInfo = $ocisClient->getOcisFileInfo($user_token, $webdavClient, $nodePath);
			$inviteData = [
				'driveId' => $personalDrives[0]['id'],
				'itemId' => $ocisFileInfo['{http://owncloud.org/ns}fileid'],
				'recipientType' => $recipientType,
				'recipientId' => $recipientId,
				'roleId' => $chosenRole['id'],
			];
			$jsonResp = $ocisClient->shareInvite($user_token, $user->getUID(), $inviteData);

			// run callback if successful
			$callback($share, $jsonResp);
		}
	}

	protected function cloneFilesForUser(IUser $user, ConflictLogFile $conflictLogFile): bool {
		$email = $user->getEMailAddress();
		if ($email === null) {
			return false;
		}

		$user_token = $this->actAsUser($user->getUID());
		$password = $this->generateAppPassword($user);
		try {
			$ocis_connection = $this->buildRCloneConnectionStringForOCIS($user->getUID(), $user_token);
			$oc10_connection = $this->buildRCloneConnectionStringForOC($user, $password);
			$this->writeln("ocis connect: $ocis_connection", true);
			$this->writeln("oc10 connect: $oc10_connection", true);

			$cmd = [
				self::$rclone_bin,
				'sync',
				$this->insecure ? '--no-check-certificate' : '',
				'--create-empty-src-dirs',
				'--ignore-case',
				'--ignore-case-sync',
				'--webdav-owncloud-exclude-shares=true',
				'--webdav-owncloud-exclude-mounts=true',
				'--config=',
				'-v',
				"$oc10_connection:/",
				"$ocis_connection:/ownCloud",
			];
			$verified = true;
			$lp = new ProcessOutputLineProcessor(function ($type, $line) use (&$verified, $user, $conflictLogFile) {
				$logLevels = ['EMERGENCY', 'ALERT', 'CRITICAL', 'ERROR', 'WARNING', 'NOTICE'];
				foreach ($logLevels as $logLevel) {
					if (str_contains($line, $logLevel)) {
						$conflictLogFile->putCSV([$logLevel, $user->getUID(), $user->getEMailAddress(), $line]);
						# notice on config file access is not blocking the migration process
						if (!(str_contains($line, 'NOTICE: Config file') && str_contains($line, 'not found - using defaults'))) {
							$verified = false;
						}
					}
				}
				echo $line . PHP_EOL;
			});
			$process = new Process($cmd);
			$process->setTimeout(null);
			$process->run($lp);

			# close the output processor
			$lp->close();

			return $verified;
		} finally {
			# cleanup app password
			$this->tokenProvider->invalidateToken($password);
		}
	}

	private function buildRCloneConnectionStringForOCIS(string $userId, string $password): string {
		$url = "https://$this->ocis_host/remote.php/webdav/";
		$obscured_password = self::RCloneObscure($password);
		$rclone_connection_elements = [
			"ocis-migrate",
			'type=webdav',
			"url=\"$url\"",
			'vendor=owncloud',
			"user=\"$userId\"",
			"pass=\"$obscured_password\"",
		];

		return implode(',', $rclone_connection_elements);
	}

	private function buildRCloneConnectionStringForOC(IUser $user, string $password): string {
		$userId = $user->getUID();
		$url = $this->generator->getAbsoluteUrl($this->generator->linkTo('', 'remote.php') . '/dav/files/' . rawurlencode($userId) . '/');
		$obscured_password = self::RCloneObscure($password);
		$connection_elements = [
			'oc-demo',
			'type=webdav',
			"url=\"$url\"",
			'vendor=owncloud',
			"user=\"$userId\"",
			"pass=\"$obscured_password\"",
		];
		return implode(',', $connection_elements);
	}

	private function generateAppPassword(IUser $user): string {
		$token = Uuid::uuid4()->toString();
		$uid = $user->getUID();

		$this->tokenProvider->generateToken($token, $uid, $uid, null, 'ocis migration');
		return $token;
	}

	public static function RCloneObscure(string $x): string {
		return exec(self::$rclone_bin . ' obscure --config= ' . escapeshellarg($x));
	}
}
